### ISSUE TITLE
Latest Widget errors

### ISSUE THREAD

**Issue by Lux-Delux** [jacobwb/hashover-next#80] opened 2015-03-22 01:37 UTC
It's getting late and not sure if I messed something up but in any case the widget didn't load and here are the log errors

`[error] 1059#0: *303800 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: path in /hashover/scripts/setup.php on line 185
PHP message: PHP Notice:  Undefined index: path in /hashover/scripts/setup.php on line 189
PHP message: PHP Warning:  array_merge(): Argument #2 is not an array in /hashover/scripts/parsejson.php on line 44
PHP message: PHP Catchable fatal error:  Argument 1 passed to DisplayComments::parse() must be of the type array, null given, called in /hashover/api/latest.php on line 95 and defined in /hashover/scripts/displaycomments.php on line 83" while reading response header from upstream`

**Comment by jacobwb** [comment] 2015-03-22 05:49
This is really confusing... you might try the latest files, I did change some things that might have been the cause. What's weird is that your `latest.php` is producing what looks like working JavaScript:

> [My first PHP page - Widget](http://tapebrain.com/hashover/api/latest.php?url=http%3A%2F%2Ftapebrain.com%2Fcmtest.php&title=My%20first%20PHP%20page)

Are you getting this error from a local instance, not over HTTP?

**Comment by Lux-Delux** [comment] 2015-03-22 11:09
Nope, only tried online. Unfortunately I developed my new theme on Windows so I wasn't able to get hashover working easily (a lesson to develop on Linux in the future argh)

I'll try with the newer files later

**Comment by jacobwb** [comment] 2015-03-23 06:45
Let me know once you've tried the newest files, I'm having a hard time reproducing it here.

Maybe try:

1. Check that the metadata files are being created, they are hidden on Unix systems. Locate one like so: `hashover/pages/cmtest-php/.metadata`. If the files are being created, post one here.

2. Check the metadata file permissions, should be 0644 (-rw-r--r--) owned by www-data.

3. If you're using JSON, try XML. I might have over looked something specific to JSON.

**Comment by Lux-Delux** [comment] 2015-03-23 11:46
Did a quick test yesterday and didn't work, need to try your suggestions later today

**Comment by Lux-Delux** [comment] 2015-03-23 22:02
Here's from a .metadata file
`"title": "Texas Chainsaw Massacre prequel Leatherface \u2022 Tapebrain",
        "url": "http:\/\/tapebrain.com\/news\/texas-chainsaw-massacre-prequel-leatherface\/",
        "status": "open",
        "latest": [
                "2-1",
                "1-1-2",
                "1-1-1",
                "1-1",
                "3",
                "2"
        ]
}`

**Comment by jacobwb** [comment] 2015-03-24 09:35
That looks fine.

You wouldn't happen to have been using the widget on the same page as the normal comments would you? Because there was a bug that caused only the last script tag to execute, or rather caused the last script to execute twice. Which is fixed now.

If it still isn't working, please post any errors that you can find. Either PHP or JavaScript. Also, it might help me to have a test page of just the widget on your server, so I can see how its behaving.

**Comment by Lux-Delux** [comment] 2015-03-24 11:15
Yeah the widget and comments were on the same page.

Didn't test thoroughly yesterday, will probably try it out again today and see if there are any problems.

**Comment by Lux-Delux** [comment] 2015-03-30 11:03
Did a quick test and the widget is now displaying properly, not seem to be getting any errors (still using JSON)

Will off course report back if I notice any strange behavior.

**Closed** 2018-02-26 15:52 UTC
