### ISSUE TITLE
Input-background-png on mobile device repeated.

### ISSUE THREAD

**Issue by prisae** [jacobwb/hashover-next#112] opened 2015-06-21 21:25 UTC
Hi Jacob,

The attached screenshots show it, and I couldn't figure out a solution myself. With the default theme, everything looks fine on the Desktop. But on my mobile (Galaxy S3, Firefox Browser) the little corpus from the png is repeated over all other fields. So it has something to do with mobile behaviour.

Thanks,
Dieter

Here how it looks on the Desktop
![desktop](https://cloud.githubusercontent.com/assets/8020943/8273404/d63617f6-1831-11e5-8c28-74d2c656d1d5.png)

Here how it looks on my mobile
![mobile](https://cloud.githubusercontent.com/assets/8020943/8273405/d78565e4-1831-11e5-9b45-b1d516e21959.png)

**Comment by jacobwb** [comment] 2015-06-22 06:00
This is now fixed.

Before these recent changes, the background image for the inputs was applied to the actual input elements, and on mobile this background image changes to use an SVG to allow them to scale nicely. Now, because Chrome started doing that stupid yellow highlight on autocompleted form inputs, which covers the background image, the theme now uses the CSS `::before` selector and sets the background image on that instead.

This bug was caused by the mobile still setting the SVG background on the actual input elements rather than their respective `::before` selectors.

Thanks for pointing it out! I haven't done much mobile testing of the new changes.

**Closed by jacobwb** 2015-06-22 06:00 UTC
Labels: bug
