### ISSUE TITLE
Weird behavour in Like links

### ISSUE THREAD

**Issue by jorgesumle** [jacobwb/hashover-next#148] opened 2017-02-25 18:40 UTC
Here is a video that shows that behaviour https://archive.org/download/bug-in-hashover-next/vokoscreen-2017-02-25_18-13-31.mkv

In mobile phones is also very difficult to simply give a Like, because it selects and the deselects very quickly.

**Comment by jacobwb** [comment] 2017-02-25 22:46
This was caused by commit a62db55c6d752ba869c2c92d527e9b11dc11bb56, where instances of `XMLHttpRequest.onload` were changed to `XMLHttpRequest.onreadystatechange`. Before this commit, the `likeComment` function would execute 1 time when the AJAX request was finished loading, now the `likeComment` function is executed at least 4 times throughout the life cycle of the AJAX request.

This is intentional, but the necessary check was not in place to ensure the like link only changes once the request has finished. This caused the `likeComment` function to change the like link multiple times.

This is now fixed.

**Closed by jacobwb** 2017-02-25 22:46 UTC
Labels: bug
